-   id: secrets_filename
    name: Check filenames for potential secrets
    description: 'Check filenames for potential secrets'
    language: python
    entry: secrets_filename

-   id: secrets_filecontent
    name: Check file content for potential secrets
    description: 'Check file content for potential secrets'
    language: python
    entry: secrets_filecontent
